# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(default='images/christine.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='jirani_pic',
            field=models.ImageField(default='images/christine.jpg', upload_to='images/'),
        ),
    ]
